version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install -g serverless
      - npm install
  build:
    commands:
      - echo Entered the build phase...
      - serverless deploy ${STAGE_NAME}
      - echo deployment completed
cache:
  paths:
    - node_modules
